<!DOCTYPE>
<html>
<head>
	<style>body{
		     background-color: lightblue;
	       }
</style>

	<marquee attribute_name="attribute_value"...more attributes>
		<h1><b>A SCHOOL MANAGEMENT SYSTEM</b></h1>
</marquee>
</head>
<body> 
<?php
	<img src="https://th.bing.com/th/id/R31083c9376c82b68e3582f5d0a56b4cb?rik=ea5mtN94CyngtQ&riu=http%3a%2f%2fwww.codewithc.com%2fwp-content%2fuploads%2f2014%2f08%2fschool-management.png&ehk=xsrSV6TBHynTU4xyN3fuz3U4I1Qi497maP0LR6ZW25g%3d&risl=&pid=ImgRaw">
	<p>
		<a href="https://th.bing.com/th/id/R31083c9376c82b68e3582f5d0a56b4cb?rik=ea5mtN94CyngtQ&riu=http%3a%2f%2fwww.codewithc.com%2fwp-content%2fuploads%2f2014%2f08%2fschool-management.png&ehk=xsrSV6TBHynTU4xyN3fuz3U4I1Qi497maP0LR6ZW25g%3d&risl=&pid=ImgRaw">
		school management system</a>
    </p>
    <p><h1><a href="#">DASHBOARD&#9660;</a></h1></p>
    <p>
        <form action="register.php" method="post">
    		<div align="left">
    	<UL class="sub-menu">
    	    	<h2><li><a href="#">Registration</a></li></h2>
    	    </UL>
    	       	    <p id="demo"></p>
    	    	<menu><dialog open>create an account</dialog>
    	    		    	    	</menu>
    	    	<button onlick="myFunction()">Sign Up</button><br>	<br>    	    	
    	      User  <select name="User">
    	    		<option value="A">Admin</option>
    	    		<option value="B">Student</option>
    	    		<option value="C">Teacher</option>
    	    	</select>
    	    	
    	     		<p id="demo"></p>
    	    		<fieldset>
    	    		<legend>Login Form</legend>
    	Name:<input type="text"size=maxlength="30" name="name"</br></br>
    	Password:<input type="text"size=maxlength="30" name="password"></br></br>
    	Birthday(date and time):<input type="datetime-local" name="bda">
    	Address:<input type="text"size=maxlength="30" name="Address">
    	rows="3"cols="30"maxlength=100></textarea></br></br>

    	Gender:<br>
    	<input type="checkbox"name="section">Male</br>
    	<input type="checkbox"name="section">Female</br></br>

    	Year:
    	<select name="Year">
    		<option value="A">First</option>
    		<option value="B">Second</option>
    		<option value="c">Third</option>
    	</select></br></br>
    	<input type="Submit"value="Submit">
       </fieldset>
    </div>
    </form>
     <script>
    function myFunction() {
    	document.getElementById('demo').innerHTML="sign here"
    } 
   </script>
</p>

 </body>
 </html>

